// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package words

import (
	"vocabulary/api/words"
	userLogic "vocabulary/internal/logic/users"
	wordsLogic "vocabulary/internal/logic/words"
)

type ControllerV1 struct{
	users *userLogic.Users
	words *wordsLogic.Words
}

func NewV1() words.IWordsV1 {
	return &ControllerV1{
		users: userLogic.New(),
		words: wordsLogic.New(),
	}
}


